# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('shortened', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_short_app.Bookmark')),
            ],
        ),
    ]
